server.port=8080

# MySQL - change password to yours
spring.datasource.url=jdbc:mysql://localhost:3306/society_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Finnoneneo@CAS
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=SocietyAppSuperSecretKeyForJWTTokenGenerationMakeIt256Bits
app.jwt.expiration-ms=86400000

logging.level.com.societyapp=DEBUG


# OR change to 5185 (see step 4)


#spring.datasource.url=jdbc:mysql://localhost:3306/platform?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#
#
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.idle-timeout=600000
#spring.datasource.hikari.connection-timeout=30000
#
#spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.format_sql=true

